// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using dataService.Domain.Models;

namespace dataService.Migrations
{
    [DbContext(typeof(MainContext))]
    partial class MainContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("dataService.Domain.Models.actions", b =>
                {
                    b.Property<long>("_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("actiondate")
                        .HasColumnType("text");

                    b.Property<string>("actiondetails")
                        .HasColumnType("text");

                    b.Property<string>("actiontype")
                        .HasColumnType("text");

                    b.Property<string>("actionuser")
                        .HasColumnType("text");

                    b.Property<float>("netfinancialchange")
                        .HasColumnType("real");

                    b.Property<int>("sponsors_id")
                        .HasColumnType("integer");

                    b.Property<long?>("sponsors_id1")
                        .HasColumnType("bigint");

                    b.HasKey("_id");

                    b.HasIndex("sponsors_id1");

                    b.ToTable("actions");
                });

            modelBuilder.Entity("dataService.Domain.Models.sponsors", b =>
                {
                    b.Property<long>("_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("contactemail")
                        .HasColumnType("text");

                    b.Property<string>("contactname")
                        .HasColumnType("text");

                    b.Property<string>("image")
                        .HasColumnType("text");

                    b.Property<string>("sponsorname")
                        .HasColumnType("text");

                    b.Property<string>("status")
                        .HasColumnType("text");

                    b.HasKey("_id");

                    b.ToTable("sponsors");
                });

            modelBuilder.Entity("dataService.Domain.Models.actions", b =>
                {
                    b.HasOne("dataService.Domain.Models.sponsors", "sponsors")
                        .WithMany("sponsoractions")
                        .HasForeignKey("sponsors_id1");

                    b.Navigation("sponsors");
                });

            modelBuilder.Entity("dataService.Domain.Models.sponsors", b =>
                {
                    b.Navigation("sponsoractions");
                });
#pragma warning restore 612, 618
        }
    }
}
